### ISSUE TITLE
Migration did not work with Postgresql.

### ISSUE THREAD

**Issue by jberall** [ListFixer/yii2-remember-me#3]
Simple fix.
'FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE'

Change to (the user needs to be "user")
'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE'

**Comment by Michael-Labriola** [comment]
That change breaks MYSQL.  I fixed it another way.  Please let me know if this works for you.  Thanks.

**Comment by jberall** [comment]
The fix worked.
Looking forward to testing out the app.
