### ISSUE TITLE
Call to undefined method listfixer\remember\RememberMe::findIdentity()

### ISSUE THREAD

**Issue by ghost** [ListFixer/yii2-remember-me#4]
![37](https://cloud.githubusercontent.com/assets/16696651/23820135/0e321cf2-0612-11e7-93f0-c57567bb2485.png)
![38](https://cloud.githubusercontent.com/assets/16696651/23820132/0e08b7d6-0612-11e7-83f6-cb9351df8c3f.png)
![39](https://cloud.githubusercontent.com/assets/16696651/23820133/0e1ff59a-0612-11e7-98d9-beb013ecc476.png)
![40](https://cloud.githubusercontent.com/assets/16696651/23820134/0e304c2e-0612-11e7-9b51-1d1d6312b289.png)

**Comment by Michael-Labriola** [comment]
Hi. Please send me the "user" section in your config file.  The identity class should not have been changed when configuring "remember me".  It probably should be "app\models\User".

**Comment by ghost** [comment]
````
'user' => [
            'identityClass' => 'listfixer\remember\RememberMe',
            'loginUrl' => ['site/login'],
            'enableAutoLogin' => true,
            'as authLog' => [
                'class' => 'yii2tech\authlog\AuthLogWebUserBehavior',
            ],
        ],

**Comment by ghost** [comment]
sorry - my mistake
with - works
````
'user' => [
            'class' => 'listfixer\remember\RememberMe',
            'identityClass' => 'common\models\User',
            'loginUrl' => ['site/login'],
            'enableAutoLogin' => true,
            'as authLog' => [
                'class' => 'yii2tech\authlog\AuthLogWebUserBehavior',
            ],
        ],

**Comment by Michael-Labriola** [comment]
Glad to hear it works.

**Comment by ghost** [comment]
I suggest you to redefine migration like [https://github.com/yii2tech/authlog](https://github.com/yii2tech/authlog) -  nobody will remember to apply migration NOT from console\migrations during deployment.
